---
- name: System summary is compiled
  hosts: win2019s01
  tasks:
    - name: Product facts are collected
      ansible.windows.setup:

    - name: Summary is written
      win_copy:
        content: |
          OS: {{ ansible_facts['os_name'] }}
          Machine ID: {{ ansible_facts['machine_id'] }}
          Last Boot: {{ ansible_facts['lastboot'] }}
        dest: "{{ ansible_facts['user_dir'] }}\\Desktop\\summary-{{ ansible_facts['hostname'] }}.txt"